# Generated by Django 5.2.17 on 2026-09-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('reported_cases', models.PositiveIntegerField(default=0)),
                ('under_investigation', models.PositiveIntegerField(default=0)),
                ('under_trial', models.PositiveIntegerField(default=0)),
                ('convicted', models.PositiveIntegerField(default=0)),
                ('acquitted', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('division', models.CharField(blank=True, max_length=60)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('reported_cases', models.PositiveIntegerField(default=0)),
                ('under_investigation', models.PositiveIntegerField(default=0)),
                ('under_trial', models.PositiveIntegerField(default=0)),
                ('convicted', models.PositiveIntegerField(default=0)),
                ('acquitted', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='report-evidence/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('INVESTIGATION', 'Under Investigation'), ('TRIAL', 'Under Trial'), ('CONVICTED', 'Convicted'), ('ACQUITTED', 'Acquitted')], max_length=30)),
                ('court_status', models.CharField(blank=True, max_length=180)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.city')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='api.city'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('city', 'name')},
        ),
    ]
