# Generated by Django 5.2.17 on 2026-09-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General public safety'), ('SEXUAL_OFFENCE', 'Sexual offence'), ('VIOLENCE', 'Violence'), ('TRAFFICKING', 'Trafficking / exploitation'), ('CYBERCRIME', 'Cybercrime')], default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='case',
            name='offence_section',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
