# Generated by Django 5.2.17 on 2026-09-25 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatthread_chatmessage_upazila_chatthread_upazila'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('price_range', models.CharField(choices=[('BUDGET', 'Budget'), ('MID', 'Mid-range'), ('PREMIUM', 'Premium')], default='BUDGET', max_length=20)),
                ('has_24h_front_desk', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_women_only_floor', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='api.city')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('rating', models.PositiveSmallIntegerField()),
                ('safety_rating', models.PositiveSmallIntegerField()),
                ('solo_traveller', models.BooleanField(default=False)),
                ('body', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.hotel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('hotel', 'user'), name='unique_review_per_user_per_hotel')],
            },
        ),
    ]
