# Generated by Django 5.2.17 on 2026-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hotel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='district-photos/'),
        ),
    ]
